@startuml SABlock

left to right direction
title SABlock

package dataset {
    object discourse_analysis_one.xlsx
    object discourse_analysis_two.xlsx
}
package CleanDataset {

}
dataset.discourse_analysis_one.xlsx --> CleanDataset
dataset.discourse_analysis_two.xlsx --> CleanDataset

@enduml


