@startuml CleanDataset Activity

title CleanDataset Activity
start
:Initialize;
-> Import libraries and excel data sheets;
:Instatiate Data;
-> remove metadata and combine simulation files;

repeat: Clean Simulations;
    :Label Columns;
    -> 0:"Turn Taking", 1:"Time", 2:"Total", 3:"Simulation", 4:"SA Team";
    :Remove Empty Values;
    -> Check for NA/NULL;
    :Drop Extra Columns;
    -> Columns > 5;
    :Format All Values Into Strings;

repeat while (More Simulations?) is (yes)
-> OUTPUT: clean_sims;
:Dump Data;
-> OUTPUT: clean_data.pickle;


stop
@enduml


