
@startuml PsuedoClassification Activity

title PsuedoClassification Activity
start
:Initialize;
-> Import libraries and clneaned data;

:Setup Prediciton Dataframe;

:Split Data;
->test size 0.25;

:Train/Test Models;
->1. DecisionTreeRegressor
2. DecisionTreeClassifier
3. RandomForestClassifier
4. RandomForestRegressor
5. SVM with K best
6. MLPClassifier - Adam
7. MLPClassifier - LBFGS;

:Log Results to Console;

stop
@enduml